use crate::utils::{CommandExt as _, Sandbox};

const MANAGED_HOOK_NAMES: [&str; 3] = ["pre-commit", "post-checkout", "pre-push"];

fn assert_hooks_installed(env: &Sandbox) {
    let hooks_dir = env.projects_root().join(".git/hooks");
    for name in MANAGED_HOOK_NAMES {
        let path = hooks_dir.join(name);
        assert!(path.exists(), "{name} should exist after install");
        let content = std::fs::read_to_string(&path).expect("read hook");
        assert!(
            content.contains("GITBUTLER_MANAGED_HOOK_V1"),
            "{name} should carry the managed-hook signature"
        );
    }
}

fn assert_hooks_not_installed(env: &Sandbox) {
    let hooks_dir = env.projects_root().join(".git/hooks");
    for name in MANAGED_HOOK_NAMES {
        let path = hooks_dir.join(name);
        if path.exists() {
            let content = std::fs::read_to_string(&path).unwrap_or_default();
            assert!(
                !content.contains("GITBUTLER_MANAGED_HOOK_V1"),
                "{name} should not be GitButler-managed"
            );
        }
    }
}

/// Install a fake prek-managed pre-commit hook in the sandbox so the install
/// command's external-manager detection fires.
fn install_fake_prek_hook(env: &Sandbox) {
    env.invoke_bash(
        "mkdir -p .git/hooks && \
         printf '#!/bin/sh\\n# File generated by prek\\nexec prek hook-impl pre-commit\\n' > .git/hooks/pre-commit && \
         chmod +x .git/hooks/pre-commit",
    );
}

#[test]
fn install_lays_down_signed_hooks_in_a_fresh_repo() -> anyhow::Result<()> {
    let env = Sandbox::open_with_default_settings("repo-no-remote")?;

    env.but("hook install").assert().success();
    assert_hooks_installed(&env);

    Ok(())
}

#[test]
fn install_is_idempotent_and_reports_already_managed() -> anyhow::Result<()> {
    let env = Sandbox::open_with_default_settings("repo-no-remote")?;

    env.but("hook install").assert().success();
    // Second invocation should also succeed and leave the hooks in place.
    env.but("hook install").assert().success();
    assert_hooks_installed(&env);

    Ok(())
}

#[test]
fn install_detects_prek_and_skips_overwriting_external_hooks() -> anyhow::Result<()> {
    let env = Sandbox::open_with_default_settings("repo-no-remote")?;
    install_fake_prek_hook(&env);

    env.but("hook install").assert().success();
    // Prek hook stays in place; GitButler did not install over it.
    let pre_commit = env.projects_root().join(".git/hooks/pre-commit");
    let content = std::fs::read_to_string(&pre_commit)?;
    assert!(content.contains("prek hook-impl"));
    assert!(!content.contains("GITBUTLER_MANAGED_HOOK_V1"));

    Ok(())
}

#[test]
fn install_force_overrides_external_manager_detection() -> anyhow::Result<()> {
    let env = Sandbox::open_with_default_settings("repo-no-remote")?;
    install_fake_prek_hook(&env);

    env.but("hook install --force").assert().success();
    // With --force, GitButler installs its hooks even with prek present.
    assert_hooks_installed(&env);

    Ok(())
}

#[test]
fn install_force_re_enables_after_persisted_disable() -> anyhow::Result<()> {
    let env = Sandbox::open_with_default_settings("repo-no-remote")?;
    install_fake_prek_hook(&env);

    // First call detects prek and persists `installHooks=false`.
    env.but("hook install").assert().success();
    assert_hooks_not_installed(&env);

    // --force flips the config back and installs.
    env.but("hook install --force").assert().success();
    assert_hooks_installed(&env);

    Ok(())
}

/// GitButler-first coexistence (the reverse of the usual prek-first flow):
/// adopt GitButler in a fresh repo, then have a hook manager (prek) take over
/// the pre-commit slot afterwards — as `prek install` would. A subsequent
/// `but hook install` must detect prek, step aside (persist the opt-out and
/// clean up its own managed hooks), and never reclaim the prek-owned hook.
#[test]
fn install_then_external_manager_takeover_steps_aside_on_reinstall() -> anyhow::Result<()> {
    let env = Sandbox::open_with_default_settings("repo-no-remote")?;

    // 1. GitButler first: managed hooks installed into a fresh repo.
    env.but("hook install").assert().success();
    assert_hooks_installed(&env);

    // 2. Later, prek claims the pre-commit slot.
    install_fake_prek_hook(&env);

    // 3. Re-running install must defer to prek rather than clobbering it.
    env.but("hook install").assert().success();

    let pre_commit = std::fs::read_to_string(env.projects_root().join(".git/hooks/pre-commit"))?;
    assert!(
        pre_commit.contains("prek hook-impl"),
        "prek-owned pre-commit should be preserved, got: {pre_commit}"
    );
    assert!(
        !pre_commit.contains("GITBUTLER_MANAGED_HOOK_V1"),
        "GitButler must not reclaim the prek-owned hook"
    );

    // GitButler steps aside entirely: its own managed hooks are cleaned up
    // rather than left orphaned alongside the external manager.
    assert_hooks_not_installed(&env);

    Ok(())
}

#[test]
fn install_emits_json_report() -> anyhow::Result<()> {
    let env = Sandbox::open_with_default_settings("repo-no-remote")?;

    let output = env
        .but("--format json hook install")
        .allow_json()
        .output()?;
    let json: serde_json::Value = serde_json::from_slice(&output.stdout)?;

    // Top-level shape: { hooks, hookManager, hooksInstalled, warnings }
    assert!(json["hooks"].is_array(), "hooks should be an array");
    assert!(
        json["hooksInstalled"].is_boolean(),
        "hooksInstalled should be a bool"
    );
    assert!(json["warnings"].is_array(), "warnings should be an array");
    // hookManager is null on a fresh repo (no external manager detected).
    assert!(
        json["hookManager"].is_null(),
        "hookManager should be null on fresh install"
    );

    let hooks = json["hooks"].as_array().unwrap();
    assert_eq!(hooks.len(), 3, "expected 3 managed hook entries");

    Ok(())
}
